UniversityManagementSystem/Models/CourseEnrollViewModel.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem.Models
{
    public class CourseEnrollViewModel
    {

        [Required]
        [Range(1,int.MaxValue)]
        public int StudentId { get; set; }
        [Required]
        public int CourseId { get; set; }
        [DisplayName("Course Code")]
        public string Code { get; set; }
        [Required]
        public string CourseName { get; set; }

        public string Grade { get; set; }
        [Required]
        [DisplayName("Date")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
    }
}

UniversityManagementSystem/Controllers/CourseEnrollController.cs
using System;
using System.Data;
using System.IO;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseEnrollController : Controller
    {
        private StudentManager studentManager = new StudentManager();
        private CourseManager courseManager = new CourseManager();
        private CourseEnrollManager courseEnrollManager=new CourseEnrollManager();
        
        // GET: CourseEnroll
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            ViewBag.Title = "Enroll in a Course";
            ViewBag.Students = studentManager.GetAllstStudents();
            return View();
        }

        [Authorize(Roles = "Teacher")]
        [HttpPost]
        public ActionResult Index(CourseEnrollViewModel courseEnroll)//int StudentId, int courseId, DateTime date)
        {
            ViewBag.Msg = courseEnrollManager.EnrollCourse(courseEnroll);
            ViewBag.Title = "Enroll in a Course";
            ViewBag.Students = studentManager.GetAllstStudents();
            ModelState.Clear();
            return View();
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult SaveStudentResult()
        {
            ViewBag.Title = "Save Student Result";
            ViewBag.Students = courseEnrollManager.GetEnrolledStudents();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult SaveStudentResult(int StudentId, int courseId, string grade)
        {
            ViewBag.Msg = courseEnrollManager.SaveResult(StudentId, courseId, grade);
            ViewBag.Title = "Save Student Result";
            ViewBag.Students = courseEnrollManager.GetEnrolledStudents();
            return View();
        }

        public ActionResult ViewStudentResult()
        {
            ViewBag.Title = "View Student Result.";
            ViewBag.Students = courseEnrollManager.GetEnrolledStudents();
            return View();
        }
        public JsonResult GetStudentById(int studentId)
        {
            var student = studentManager.GetStudentById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByStudentId(int studentId)
        {
            var student = studentManager.GetStudentById(studentId);
            var courses = courseManager.GetCourseByStudent(student);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetEnrollledCourseByStudentId(int studentId)
        {
            var courses = courseEnrollManager.GetEnrolledCourseByStudentId(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetIncompletePrerequisite(int studentId, int courseId)
        {
            var prereq = courseEnrollManager.GetIncompletePrerequisite(studentId, courseId);
            return Json(prereq, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetResultById(int studentId)
        {
            var courses = courseEnrollManager.GetResultById(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreatePdf(int studentId)
        {
            var result = courseEnrollManager.GetResultById(studentId);
            var student = studentManager.GetStudentById(studentId);

            //pdf er code
            var doc = new Document(PageSize.A4, 50, 50, 25, 25);
            var stream = new MemoryStream();

            PdfWriter writer = PdfWriter.GetInstance(doc, stream);

            //writer.PageEvent = new PDFHeader("Result");

            doc.Open();
            Paragraph heading = new Paragraph("Bangladesh University of Business & Technology\nResult", FontFactory.GetFont("Times New Roman", 20, Font.BOLD));
            heading.Alignment = Element.ALIGN_LEFT;
            doc.Add(heading);

            Paragraph p = new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(0.0F, 100.0F, BaseColor.BLACK, Element.ALIGN_LEFT, 1)));
            doc.Add(p);

            var HeaderTable = new PdfPTable(2);
            HeaderTable.HorizontalAlignment = 0;
            HeaderTable.SpacingBefore = 20;
            HeaderTable.SpacingAfter = 10;
            HeaderTable.DefaultCell.Border = 0;
            HeaderTable.SetWidths(new int[] { 3, 6 });

            HeaderTable.AddCell(new Phrase("Student Reg. No. ", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            HeaderTable.AddCell(new Phrase(student.RegistrationNo));
            HeaderTable.AddCell(new Phrase("Student Name ", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            HeaderTable.AddCell(new Phrase(student.Name));
            HeaderTable.AddCell(new Phrase("Student Email ", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            HeaderTable.AddCell(new Phrase(student.Email));
            HeaderTable.AddCell(new Phrase("Department ", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            HeaderTable.AddCell(new Phrase(student.DepartmentName.Name));

            doc.Add(HeaderTable);

            var DetailTable = new PdfPTable(3);
            DetailTable.HorizontalAlignment = 0;
            DetailTable.SpacingAfter = 10;
            DetailTable.DefaultCell.Border = 0;
            DetailTable.SetWidths(new int[] { 6, 10, 3 });
            DetailTable.WidthPercentage = 100;
            DetailTable.DefaultCell.Border = Rectangle.BOX;

            DetailTable.AddCell(new Phrase("Course Code", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            DetailTable.AddCell(new Phrase("Course Name", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));
            DetailTable.AddCell(new Phrase("Grade", FontFactory.GetFont("Times New Roman", 12, Font.BOLD)));

            foreach (var Line in result)
            {
                DetailTable.AddCell(new Phrase(Line.Code));
                DetailTable.AddCell(new Phrase(Line.CourseName));
                DetailTable.AddCell(new Phrase(Line.Grade));
            }
            doc.Add(DetailTable);

            doc.Add(p);

            Paragraph foot = new Paragraph("Develped By Team CodeRiders.");
            foot.Alignment = Element.ALIGN_LEFT;
            doc.Add(foot);

            doc.Close();
            //pdf er code sesh...

            //download er code
            byte[] bytes = stream.ToArray();
            stream.Close();
            Response.Clear();
            Response.ContentType = "application/pdf";
            Response.AddHeader("Content-Disposition", "attachment; filename=" + student.RegistrationNo + ".pdf");
            Response.ContentType = "application/pdf";
            Response.Buffer = true;
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.BinaryWrite(bytes);
            Response.End();
            Response.Close();
            //download sesh...
            ModelState.Clear();
            return View();
        }
    }
}

UniversityManagementSystem/Views/CourseEnroll/Index.cshtml
@using UniversityManagementSystem.Models
@model UniversityManagementSystem.Models.CourseEnrollViewModel
@{
    List<Student> students = ViewBag.Students;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p style="color: blue">@ViewBag.Msg</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="col-md-2 control-label">Student Reg. No.</label>
            <div class="col-md-10">
                @*<select class="form-control" id="StudentId" name="StudentId">
                    <option value="-1">--Select--</option>
                    @if (students != null)
                    {
                        foreach (Student VARIABLE in students)
                        {
                            <option value="@VARIABLE.Id">@VARIABLE.RegistrationNo</option>
                        }
                    }
                </select>*@
                @Html.DropDownListFor(model => model.StudentId, new SelectList(students, "Id", "RegistrationNo"), "--Select--", new { @class = "form-control"})
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Name</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="StudentName" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Email</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="Email" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Department</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="Department" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Select Course</label>
            <div class="col-md-10">
                <select class="form-control" id="CourseId" name="CourseId">
                    <option value="-1">--Select--</option>
                </select>
                <span id="prereqChk" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Date, new { @class = "form-control datePicker" })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datePicker", @Value = DateTime.Today.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                @*<input type="text" class="form-control " id="date" name="date" />
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enroll" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $(function () {
                $(".datePicker").datepicker({
                     dateFormat: 'mm/dd/yy', type: Text
                }).datepicker("setDate", "0");
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            //debugger;

            $("#StudentId").change(function () {

                var studentId = $("#StudentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="-1">--Select--</option>');
                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");
                var student = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(student),
                    success: function (data) {
                        $("#StudentName").val(data.Name);
                        $("#Email").val(data.Email);
                        $("#Department").val(data.DepartmentName.Name);
                    }
                });
                var courses = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByStudentId", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(courses),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                        });
                    }
                });
            });

            $("#CourseId").change(function () {
                $("#prereqChk").html("");
                $(':input[type="submit"]').prop('disabled', false);

                var studentId = $("#StudentId").val();
                var courseId = $("#CourseId").val();
                if (courseId == -1) return;
                //console.log(studentId + " " + courseId);

                var params = { studentId: studentId, courseId: courseId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetIncompletePrerequisite", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(params),
                    success: function (data) {
                        if (data != null) {
                            console.log(JSON.stringify(data));
                            $("#prereqChk").html("Please complete the prerequisite course first. Code: "
                                + data.Code + " Name: " + data.Name + ".");
                            $(':input[type="submit"]').prop('disabled', true);
                        }
                    }
                })
            });
        });
    </script>
}

UniversityManagementSystem/Views/CourseEnroll/SaveStudentResult.cshtml
@using UniversityManagementSystem.Models

@{
    List<Student> students = ViewBag.Students;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p style="color: blue">@ViewBag.Msg</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="col-md-2 control-label">Student Reg. No.</label>
            <div class="col-md-10">
                <select class="form-control" id="StudentId" name="StudentId">
                    <option value="-1">--Select--</option>
                    @if (students != null)
                    {
                        foreach (Student VARIABLE in students)
                        {
                            <option value="@VARIABLE.Id">@VARIABLE.RegistrationNo</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Name</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="StudentName" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Email</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="Email" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Department</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="Department" />
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Select Course</label>
            <div class="col-md-10">
                <select class="form-control" id="courseId" name="courseId">
                    <option value="-1">--Select--</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Select Grade Letter</label>
            <div class="col-md-10">
                <select class="form-control" id="grade" name="grade">
                    <option value="-1">--Select--</option>
                    <option value="A+">A+</option>
                    <option value="A">A</option>
                    <option value="A-">A-</option>
                    <option value="B+">B+</option>
                    <option value="B">B</option>
                    <option value="B-">B-</option>
                    <option value="C+">C+</option>
                    <option value="C">C</option>
                    <option value="C-">C-</option>
                    <option value="D+">D+</option>
                    <option value="D">D</option>
                    <option value="D-">D-</option>
                    <option value="F">F</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts
{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script>
        $(document).ready(function () {
            //debugger;

            $("#StudentId").change(function () {

                var studentId = $("#StudentId").val();
                $("#courseId").empty();
                $("#courseId").append('<option value="-1">--Select--</option>');
                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");
                $("#grade").val("--Select--");
                var student = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(student),
                    success: function(data) {
                        $("#StudentName").val(data.Name);
                        $("#Email").val(data.Email);
                        $("#Department").val(data.DepartmentName.Name);
                    }
                });
                var courses = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetEnrollledCourseByStudentId", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(courses),
                    success: function(data) {
                        $.each(data, function(key, value) {
                            $("#courseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                        });
                    }
                });
            });
        });
    </script>
}

UniversityManagementSystem/Views/CourseEnroll/ViewStudentResult.cshtml
@using UniversityManagementSystem.Models
@model IEnumerable<UniversityManagementSystem.Models.CourseEnrollViewModel>

@{
    List<Student> students = ViewBag.Students;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Student Result</h2>
<hr />
<div class="form-horizontal">
    <div class="form-group">
        <label class="col-md-2 control-label">Student Reg. No.</label>
        <div class="col-md-10">
            <select class="form-control" id="StudentId" name="StudentId">
                <option value="-1">--Select--</option>
                @if (students != null)
            {
                foreach (Student VARIABLE in students)
                {
                        <option value="@VARIABLE.Id">@VARIABLE.RegistrationNo</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Name</label>
        <div class="col-md-10">
            <input type="text" disabled class="form-control" id="StudentName" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Email</label>
        <div class="col-md-10">
            <input type="text" disabled class="form-control" id="Email" />
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-2 control-label">Department</label>
        <div class="col-md-10">
            <input type="text" disabled class="form-control" id="Department" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="button" disabled id="pdfBtn" value="Make PDF" class="btn btn-default form-control"
                   onclick="location.href='@Url.Action("CreatePdf","CourseEnroll")?studentId=' + $('#StudentId').val()" />
        </div>
    </div>

</div>

<table class="table" id="dataTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
        <th></th>
    </tr>
</table>


@section scripts
{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#StudentId").change(function() {

                var studentId = $("#StudentId").val();
                if (studentId === "-1") {
                    document.getElementById("pdfBtn").disabled = true;
                } else {
                    document.getElementById("pdfBtn").disabled = false;
                }
                $("#StudentName").val("");
                $("#Email").val("");
                $("#Department").val("");
                var student = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "CourseEnroll")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(student),
                    success: function(data) {
                        $("#StudentName").val(data.Name);
                        $("#Email").val(data.Email);
                        $("#Department").val(data.DepartmentName.Name);
                    }
                });
                var myTable = document.getElementById("dataTable");
                var rowCount = myTable.rows.length;
                while (--rowCount) myTable.deleteRow(rowCount);
                var json = { StudentId: studentId };
                $.ajax({
                    type: "POST",
                    url: 'GetResultById/' + studentId,
                    contentType: "application/json;charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        $.each(data, function(key, value) {
                            var table = document.getElementById("dataTable");
                            var row = table.insertRow(key + 1);
                            var cell1 = row.insertCell(0);
                            var cell2 = row.insertCell(1);
                            var cell3 = row.insertCell(2);
                            cell1.innerHTML = value.Code;
                            cell2.innerHTML = value.CourseName;
                            cell3.innerHTML = value.Grade;
                        });
                    }
                });
            });
        })
    </script>
}