UniversityManagementSystem/Controllers/ClassroomController.cs
using System;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class ClassroomController : Controller
    {
        private DepartmentManager departmentManager = new DepartmentManager();
        private ScheduleManager scheduleManager = new ScheduleManager();
        private CourseManager courseManager = new CourseManager();

        // GET: Classroom
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            ViewBag.Title = "Allocate Classroom";
            ViewBag.Departments = departmentManager.GetallDepartments();
            ViewBag.Rooms = scheduleManager.GetAllRooms();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Index(int courseId, int roomId, string day, int fromTimehr, int fromTimemn, string fromampm, int toTimehr, int toTimemn, string toampm)
        {
            ViewBag.Msg = scheduleManager.AllocateRoom(new Schedule()
            {
                CourseId = courseId,
                RoomId = roomId,
                Day = day,
                FromTime = DateTime.Parse(fromTimehr + ":" + fromTimemn + " " + fromampm),
                ToTime = DateTime.Parse(toTimehr + ":" + toTimemn + " " + toampm)
        });
            ViewBag.Title = "Allocate Classroom";
            ViewBag.Departments = departmentManager.GetallDepartments();
            ViewBag.Rooms = scheduleManager.GetAllRooms();
            ModelState.Clear();
            return View();
        }

        public ActionResult ViewClassSchedule()
        {
            ViewBag.Title = "Room Alocation Info";
            ViewBag.Departments = departmentManager.GetallDepartments();
            return View();
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult UnallocateRooms()
        {
            ViewBag.Title = "Unallocate Rooms";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult UnallocateRooms(bool id)
        {
            if (id) ViewBag.Msg = scheduleManager.UnallocateAllRooms();
            ViewBag.Title = "Unallocate Rooms";
            return View();
        }

        public JsonResult GetScheduleByDept(int departmentId)
        {
            var schedules = scheduleManager.GetScheduleByDept(departmentId);
            return Json(schedules, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByDept(int deptId)
        {
            var courses = courseManager.GetCourseByDept(deptId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystem/Controllers/CourseController.cs
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        private CourseManager courseManager = new CourseManager();
        private DepartmentManager departmentManager = new DepartmentManager();
        private SemesterManager semesterManager = new SemesterManager();

        // GET: Course
        [Authorize(Roles = "Teacher")]
        public ActionResult SaveCourse()
        {
            ViewBag.Departments = departmentManager.GetallDepartments();
            ViewBag.Semesters = semesterManager.GetAllSemesters();
            ViewBag.Prereqs = courseManager.GetAllCourse();
            ViewBag.Title = "Save Course";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult SaveCourse(Course course)
        {
            ViewBag.Msg = courseManager.SaveCourse(course);
            ViewBag.Departments = departmentManager.GetallDepartments();
            ViewBag.Semesters = semesterManager.GetAllSemesters();
            ViewBag.Prereqs = courseManager.GetAllCourse();
            ViewBag.Title = "Save Course";
            ModelState.Clear();
            return View();
        }
    }
}

UniversityManagementSystem/Controllers/DepartmentController.cs
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class DepartmentController : Controller
    {
        private DepartmentManager departmentManager = new DepartmentManager();

        // GET: Department
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            ViewBag.Title = "Save Department";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Index(Department department)
        {
            ViewBag.Title = "Save Department";
            ViewBag.Msg = departmentManager.SaveDepartment(department);
            ModelState.Clear();
            return View();
        }

        public ActionResult ViewDepartments()
        {
            ViewBag.Title = "View Departments";
            return View(departmentManager.GetallDepartments());
        }
    }
}

UniversityManagementSystem/Controllers/StudentController.cs
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class StudentController : Controller
    {
        private DepartmentManager departmentManager = new DepartmentManager();
        private StudentManager studentManager = new StudentManager();
        private AppUserManager appUserManager = new AppUserManager();

        // GET: Student
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            ViewBag.Department = departmentManager.GetallDepartments();

            ViewBag.Title = "Register Student";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Index(Student student)
        {
            //student.UserId = user.Id;
            appUserManager.CreateUser(student);
            ViewBag.Msg = studentManager.SaveStudent(student);
            var departments = departmentManager.GetallDepartments();
            ViewBag.Department = departments;
            ViewBag.Title = "Register Student";
            if (ViewBag.Msg != "Registered successfully.") return View();

            student.DepartmentName = departments.First(e => e.Id == student.DepartmentName.Id);
            return View("Details", student);
        }

        // GET: Student/Details/5
        public ActionResult Details()
        {
            return View();
        }
    }
}

UniversityManagementSystem/Views/Shared/_Layout.cshtml
@{
    bool show = User.IsInRole("Teacher");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BUBT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        .dropdown:hover .dropdown-menu {
            display: block;
        }
    </style>
    @RenderSection("styles", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BUBT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Departments<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @if (show)
                            {
                                <li>@Html.ActionLink("Save Department", "Index", "Department")</li>
                            }
                            <li>@Html.ActionLink("View Departments", "ViewDepartments", "Department")</li>
                        </ul>
                        @if (User.IsInRole("Teacher"))
                        {
                        <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Teacher")</li>
                        }

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Course<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Teacher"))
                                {
                                    <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
                                    <li>@Html.ActionLink("Course Assign", "Index", "CourseTeacher")</li>
                                    <li>@Html.ActionLink("Unassign All Courses", "UnassignCourses", "CourseTeacher")</li>
                                }
                                <li>@Html.ActionLink("Course Statics", "ViewStatic", "CourseTeacher")</li>
                            </ul>

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Student<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Teacher"))
                                {
                                <li>@Html.ActionLink("Register Student", "Index", "Student")</li>
                                <li>@Html.ActionLink("Enroll Course", "Index", "CourseEnroll")</li>
                                <li>@Html.ActionLink("Save Student Result", "SaveStudentResult", "CourseEnroll")</li>
                                }
                                <li>@Html.ActionLink("View Student Result", "ViewStudentResult", "CourseEnroll")</li>
                            </ul>

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Classrooms<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Teacher"))
                                {
                                    <li>@Html.ActionLink("Allocate Classrooms", "Index", "Classroom")</li>
                                    <li>@Html.ActionLink("Unallocate Classrooms", "UnallocateRooms", "Classroom")</li>
                                }
                                <li>@Html.ActionLink("View Class Schedule", "ViewClassSchedule", "Classroom")</li>
                            </ul>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - BUBT</p>
            </footer>
        </div>
        <script src="~/Scripts/jquery-1.12.4.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    </body>
</html>