UniversityManagementSystem/Models/CourseTeacherViewModel.cs
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem.Models
{
    public class CourseTeacherViewModel
    {
        [Required]
        [Range(1, int.MaxValue)]
        public int CourseId { get; set; }
        [Required]
        [MinLength(5, ErrorMessage = "Code must be at least 5 character.")]
        [DisplayName("Code")]
        public string CourseCode { get; set; }
        [Required]
        [DisplayName("Name/Title")]
        public string CourseName { get; set; }
        [DisplayName("Semester")]
        public string CourseSemester { get; set; }

        [Required]
        [Range(1, int.MaxValue)]
        public int TeacherId { get; set; }
        [Required]
        [DisplayName("Assigned To")]
        public string TeacherName { get; set; }

    }
}

UniversityManagementSystem/Controllers/CourseTeacherController.cs
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseTeacherController : Controller
    {
        private CourseTeacherManager courseTeacherManager = new CourseTeacherManager();
        private DepartmentManager departmentManager = new DepartmentManager();
        private TeacherManager teacherManager = new TeacherManager();
        private CourseManager courseManager = new CourseManager();

        // GET: CourseTeacher
        [Authorize(Roles = "Teacher")]
        public ActionResult Index()
        {
            ViewBag.Title = "Course Assign";
            ViewBag.Departments = departmentManager.GetallDepartments();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Index(int courseId, int teacherId)
        {
            ViewBag.Msg = courseTeacherManager.AssignCourse(courseId, teacherId);
            ViewBag.Title = "Course Assign";
            ViewBag.Departments = departmentManager.GetallDepartments();
            return View();
        }

        public ActionResult ViewStatic()
        {
            ViewBag.Title = "Course Static";
            ViewBag.Departments = departmentManager.GetallDepartments();
            return View();
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult UnassignCourses()
        {
            ViewBag.Title = "Unassign Courses";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult UnassignCourses(bool id)
        {
            if(id) ViewBag.Msg = courseTeacherManager.UnassignAllCourses();
            ViewBag.Title = "Unassign Courses";
            return View();
        }

        public JsonResult GetStaticByDept(int departmentId)
        {
            var statics = courseTeacherManager.GetCourseStaticByDept(departmentId);
            return Json(statics, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeacherByDept(int deptId)
        {
            var teachers = teacherManager.GetTeacherByDept(deptId);
            return Json(teachers, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseByDept(int deptId)
        {
            var courses = courseManager.GetUnassignedCourse(deptId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseById(int courseId)
        {
            var course = courseManager.GetCourseById(courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeacherById(int teacherId)
        {
            var teacher = teacherManager.GetTeacherById(teacherId);
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }
    }
}

UniversityManagementSystem/Views/CourseTeacher/Index.cshtml
@using UniversityManagementSystem.Models

@{
    List<Department> departments = ViewBag.Departments;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Course Assign to Teacher</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <p style="color: blue">@ViewBag.Msg</p>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="col-md-2 control-label">Department</label>
            <div class="col-md-10">
                <select class="form-control" id="deptId">
                    <option value="-1">--Select--</option>
                    @if (departments != null)
                    {
                        foreach (Department VARIABLE in departments)
                        {
                            <option value="@VARIABLE.Id">@VARIABLE.Name</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Teacher</label>
            <div class="col-md-10">
                <select class="form-control" id="teacherId" name="teacherId">
                    <option value="-1">--Select--</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Credit to be taken</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="creditToBeTaken"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Remaining credit</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="remainingCredit"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Course Code</label>
            <div class="col-md-10">
                <select class="form-control" id="courseId" name="courseId">
                    <option value="-1">--Select--</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Name</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="courseName"/>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-2 control-label">Credit</label>
            <div class="col-md-10">
                <input type="text" disabled class="form-control" id="courseCredit"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submitBtn" value="Assign" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section scripts
{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script>
        $(document).ready(function () {

            $("#deptId").change(function() {

                var dept = $("#deptId").val();
                $("#teacherId").empty();
                $("#teacherId").append('<option value="-1">--Select--</option>');
                $("#courseId").empty();
                $("#courseId").append('<option value="-1">--Select--</option>');
                $("#creditToBeTaken").val("");
                $("#remainingCredit").val("");
                $("#courseName").val("");
                $("#courseCredit").val("");
                var teachers = { deptId: dept };
                var courses = { deptId: dept };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherByDept", "CourseTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(teachers),
                    success: function(data) {
                        //alert(data);
                        $.each(data, function(key, value) {
                            //alert(key);
                            $("#teacherId").append('<option value=' + value.Id + '>' + value.Name + '</option>');
                        });
                    }
                });

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDept", "CourseTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(courses),
                    success: function(data) {
                        $.each(data, function(key, value) {
                            $("#courseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');
                        });
                    }
                });
            });

            $("#teacherId").change(function() {

                var tId = $("#teacherId").val();
                var teacher = { teacherId: tId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherById", "CourseTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(teacher),
                    success: function (data) {
                        $("#creditToBeTaken").val(data.CreditToBeTaken);
                        $("#remainingCredit").val(data.CreditToBeTaken - data.CreditTaken);
                    }
                });
            });
            
            $("#courseId").change(function () {

                var cId = $("#courseId").val();
                var course = { courseId: cId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseById", "CourseTeacher")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(course),
                    success: function (data) {
                        $("#courseName").val(data.Name);
                        $("#courseCredit").val(data.Credit);
                        
                        if(document.getElementById("remainingCredit").value<data.Credit)
                            if (confirm("Are you sure to assign this course?")) {
                                document.getElementById("submitBtn").disabled = false;
                            } else {
                                document.getElementById("submitBtn").disabled = true;
                            }
                    }
                });
            });
        });
    </script>
}

UniversityManagementSystem/Views/CourseTeacher/UnassignCourses.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unassign All Course</h2>
<br />

@using (Html.BeginForm())
{
    <p style="color: blue">@ViewBag.Msg</p>
    <button type="submit" class="btn btn-default" id="unassignBtn" value="" name="id"
            style="width: 20%; color: red" onclick="Function()">
        Unassign Courses
    </button>
}

@section scripts
{
    <script type="text/javascript">
        function Function() {
            if (confirm("Are you sure to unassign all courses?")) {
                document.getElementById("unassignBtn").value = true;
            } else {
                document.getElementById("unassignBtn").value = false;
            }
        }
    </script>
}

UniversityManagementSystem/Views/CourseTeacher/ViewStatic.cshtml
@using UniversityManagementSystem.Models

@{
    List<Department> departments = ViewBag.Departments;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>View Course Static</h2><br/>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            <label class="control-label col-md-2">Department</label>
            <div class="col-md-10">
                <select class="form-control" name="departmentId" id="departmentId">
                    <option value="-1">--Select--</option>
                    @if (departments != null)
                    {
                        foreach (Department VARIABLE in departments)
                        {
                            <option value="@VARIABLE.Id">@VARIABLE.Name</option>
                        }
                    }
                </select>
            </div>
        </div>
    </div>

    <h4>Course Information</h4>

    <table class="table" id="dataTable">
        <tr>
            <th>
                Code
            </th>
            <th>
                Name/Title
            </th>
            <th>
                Semester
            </th>
            <th>
                Assigned To
            </th>
        </tr>

        @*@foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CourseSemester)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TeacherName)
                </td>
            </tr>
        }*@

    </table>
}

@section scripts
{
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script>
        $(document).ready(function() {
            $("#departmentId").change(function() {
                var deptId = $("#departmentId").val();
                //$("tbody#dataTable tr").remove();
                var myTable = document.getElementById("dataTable");
                var rowCount = myTable.rows.length;
                while (--rowCount) myTable.deleteRow(rowCount);
                var json = { departmentId: deptId };
                $.ajax({
                    type: "POST",
                    url: 'GetStaticByDept/'+deptId,//'@Url.Action("GetStaticByDept","CourseTeacher")',
                    contentType: "application/json;charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        $.each(data, function(key, value) {
                            var table = document.getElementById("dataTable");
                            var row = table.insertRow(key+1);
                            var cell1 = row.insertCell(0);
                            var cell2 = row.insertCell(1);
                            var cell3 = row.insertCell(2);
                            var cell4 = row.insertCell(3);
                            cell1.innerHTML = value.CourseCode;
                            cell2.innerHTML = value.CourseName;
                            cell3.innerHTML = value.CourseSemester;
                            cell4.innerHTML = value.TeacherName;
                        });
                    }
                });
            });
        })
    </script>
}